"""ilk_sema

Revision ID: 11e9bbe34089
Revises: 
Create Date: 2026-08-02 17:18:20.965746
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# JSONB sütunları için gerekli; Alembic bu import'u kendiliğinden eklemiyor.
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

revision: str = '11e9bbe34089'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_species',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name_tr', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=True),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('spread_mm', sa.Integer(), nullable=False),
    sa.Column('sow_depth_mm', sa.Integer(), nullable=False),
    sa.Column('days_to_harvest', sa.Integer(), nullable=False),
    sa.Column('water_ml_per_day', sa.Integer(), nullable=False),
    sa.Column('sun_requirement', sa.Enum('FULL', 'PARTIAL', 'SHADE', name='sunrequirement', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plant_species'))
    )
    with op.batch_alter_table('plant_species', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_species_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('devices',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('serial_number', sa.String(length=120), nullable=True),
    sa.Column('firmware_version', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('indoor', sa.Boolean(), nullable=False),
    sa.Column('bed_width_mm', sa.Integer(), nullable=False),
    sa.Column('bed_length_mm', sa.Integer(), nullable=False),
    sa.Column('max_z_mm', sa.Integer(), nullable=False),
    sa.Column('safe_height_mm', sa.Integer(), nullable=False),
    sa.Column('soil_height_mm', sa.Integer(), nullable=False),
    sa.Column('mqtt_username', sa.String(length=120), nullable=True),
    sa.Column('mqtt_password_hash', sa.String(length=255), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('last_x', sa.Float(), nullable=False),
    sa.Column('last_y', sa.Float(), nullable=False),
    sa.Column('last_z', sa.Float(), nullable=False),
    sa.Column('camera_stream_url', sa.String(length=500), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('serial_number', name=op.f('uq_devices_serial_number'))
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('curves',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('curve_type', sa.Enum('WATER', 'SPREAD', 'HEIGHT', name='curvetype', native_enum=False), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_curves_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curves'))
    )
    with op.batch_alter_table('curves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curves_device_id'), ['device_id'], unique=False)

    op.create_table('farm_events',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('executable_type', sa.Enum('SEQUENCE', 'REGIMEN', name='executabletype', native_enum=False), nullable=False),
    sa.Column('executable_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repeat_every', sa.Integer(), nullable=False),
    sa.Column('time_unit', sa.Enum('NEVER', 'MINUTELY', 'HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='timeunit', native_enum=False), nullable=False),
    sa.Column('body', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_farm_events_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_events'))
    )
    with op.batch_alter_table('farm_events', schema=None) as batch_op:
        batch_op.create_index('ix_events_device_next', ['device_id', 'is_active', 'next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_farm_events_device_id'), ['device_id'], unique=False)

    op.create_table('images',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_images_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index('ix_images_device_captured', ['device_id', 'captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_device_id'), ['device_id'], unique=False)

    op.create_table('logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'SUCCESS', 'WARN', 'ERROR', name='loglevel', native_enum=False), nullable=False),
    sa.Column('channels', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_logs_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs'))
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_logs_device_created', ['device_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_logs_device_id'), ['device_id'], unique=False)

    op.create_table('peripherals',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('pin', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_peripherals_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_peripherals'))
    )
    with op.batch_alter_table('peripherals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_peripherals_device_id'), ['device_id'], unique=False)

    op.create_table('point_groups',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('point_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('criteria', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('sort_type', sa.Enum('XY_ASCENDING', 'YX_ASCENDING', 'RANDOM', 'NEAREST', name='pointgroupsort', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_point_groups_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_point_groups'))
    )
    with op.batch_alter_table('point_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_point_groups_device_id'), ['device_id'], unique=False)

    op.create_table('regimens',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_regimens_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regimens'))
    )
    with op.batch_alter_table('regimens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regimens_device_id'), ['device_id'], unique=False)

    op.create_table('sensors',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('pin', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_sensors_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensors'))
    )
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensors_device_id'), ['device_id'], unique=False)

    op.create_table('sequences',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('body', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('args', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('folder', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_sequences_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sequences'))
    )
    with op.batch_alter_table('sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sequences_device_id'), ['device_id'], unique=False)

    op.create_table('tools',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('flow_rate_ml_per_s', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='toolstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_tools_device_id_devices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tools'))
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tools_device_id'), ['device_id'], unique=False)

    op.create_table('points',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('point_type', sa.Enum('PLANT', 'WEED', 'TOOL_SLOT', 'MARKER', name='pointtype', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('radius_mm', sa.Float(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('species_id', sa.Uuid(), nullable=True),
    sa.Column('stage', sa.Enum('PLANNED', 'PLANTED', 'SPROUTED', 'ACTIVE', 'HARVESTED', 'REMOVED', name='plantstage', native_enum=False), nullable=False),
    sa.Column('planted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('depth_mm', sa.Integer(), nullable=True),
    sa.Column('water_curve_id', sa.Uuid(), nullable=True),
    sa.Column('spread_curve_id', sa.Uuid(), nullable=True),
    sa.Column('height_curve_id', sa.Uuid(), nullable=True),
    sa.Column('tool_id', sa.Uuid(), nullable=True),
    sa.Column('pullout_direction', sa.SmallInteger(), nullable=False),
    sa.Column('gantry_mounted', sa.Boolean(), nullable=False),
    sa.Column('discarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_points_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['height_curve_id'], ['curves.id'], name=op.f('fk_points_height_curve_id_curves'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['species_id'], ['plant_species.id'], name=op.f('fk_points_species_id_plant_species'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['spread_curve_id'], ['curves.id'], name=op.f('fk_points_spread_curve_id_curves'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], name=op.f('fk_points_tool_id_tools'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['water_curve_id'], ['curves.id'], name=op.f('fk_points_water_curve_id_curves'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_points'))
    )
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_points_device_type', ['device_id', 'point_type'], unique=False)
        batch_op.create_index('ix_points_device_xy', ['device_id', 'x', 'y'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_discarded_at'), ['discarded_at'], unique=False)

    op.create_table('regimen_items',
    sa.Column('regimen_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_id', sa.Uuid(), nullable=False),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['regimen_id'], ['regimens.id'], name=op.f('fk_regimen_items_regimen_id_regimens'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], name=op.f('fk_regimen_items_sequence_id_sequences'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regimen_items'))
    )
    with op.batch_alter_table('regimen_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regimen_items_regimen_id'), ['regimen_id'], unique=False)

    op.create_table('sensor_readings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=True),
    sa.Column('pin', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_sensor_readings_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_sensor_readings_sensor_id_sensors'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sensor_readings'))
    )
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.create_index('ix_readings_device_sensor_time', ['device_id', 'sensor_id', 'read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_readings_device_id'), ['device_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_readings_device_id'))
        batch_op.drop_index('ix_readings_device_sensor_time')

    op.drop_table('sensor_readings')
    with op.batch_alter_table('regimen_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regimen_items_regimen_id'))

    op.drop_table('regimen_items')
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_discarded_at'))
        batch_op.drop_index('ix_points_device_xy')
        batch_op.drop_index('ix_points_device_type')
        batch_op.drop_index(batch_op.f('ix_points_device_id'))

    op.drop_table('points')
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tools_device_id'))

    op.drop_table('tools')
    with op.batch_alter_table('sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sequences_device_id'))

    op.drop_table('sequences')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensors_device_id'))

    op.drop_table('sensors')
    with op.batch_alter_table('regimens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regimens_device_id'))

    op.drop_table('regimens')
    with op.batch_alter_table('point_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_point_groups_device_id'))

    op.drop_table('point_groups')
    with op.batch_alter_table('peripherals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_peripherals_device_id'))

    op.drop_table('peripherals')
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_device_id'))
        batch_op.drop_index('ix_logs_device_created')
        batch_op.drop_index(batch_op.f('ix_logs_created_at'))

    op.drop_table('logs')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_device_id'))
        batch_op.drop_index('ix_images_device_captured')

    op.drop_table('images')
    with op.batch_alter_table('farm_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farm_events_device_id'))
        batch_op.drop_index('ix_events_device_next')

    op.drop_table('farm_events')
    with op.batch_alter_table('curves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curves_device_id'))

    op.drop_table('curves')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))

    op.drop_table('devices')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('plant_species', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_species_slug'))

    op.drop_table('plant_species')
    # ### end Alembic commands ###
