"""uyari_kurallari_ve_bildirimler

Revision ID: 6d96e821fbab
Revises: 11e9bbe34089
Create Date: 2026-08-02 17:59:01.584936
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Alembic, JSONB sütunlarını `postgresql.JSONB(astext_type=Text())` olarak üretir
# ama `Text` import'unu eklemez. Şablona koyarak her göçte hazır bulunduruyoruz.
from sqlalchemy import Text  # noqa: F401


revision: str = '6d96e821fbab'
down_revision: Union[str, None] = '11e9bbe34089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('SENSOR_THRESHOLD', 'DEVICE_OFFLINE', name='alertkind', native_enum=False), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'SUCCESS', 'WARN', 'ERROR', name='loglevel', native_enum=False), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=True),
    sa.Column('comparison', sa.Enum('BELOW', 'ABOVE', name='alertcomparison', native_enum=False), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('offline_minutes', sa.Integer(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_alert_rules_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], name=op.f('fk_alert_rules_sensor_id_sensors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_device_id'), ['device_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'SUCCESS', 'WARN', 'ERROR', name='loglevel', native_enum=False), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_notifications_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_notifications_rule_id_alert_rules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_notifications_device_read', ['device_id', 'read_at', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_device_read')
        batch_op.drop_index(batch_op.f('ix_notifications_device_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_device_id'))

    op.drop_table('alert_rules')
    # ### end Alembic commands ###
