"""ajan_token_ve_sensor_kanallari

Revision ID: 40d861040de5
Revises: 6d96e821fbab
Create Date: 2026-08-17 19:19:00.736988
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Alembic, JSONB sütunlarını `postgresql.JSONB(astext_type=Text())` olarak üretir
# ama `Text` import'unu eklemez. Şablona koyarak her göçte hazır bulunduruyoruz.
from sqlalchemy import Text  # noqa: F401


revision: str = '40d861040de5'
down_revision: Union[str, None] = '6d96e821fbab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Ajan token'ı, servo alanları ve kanal tabanlı sensörler.

    Otomatik üretilen sürüm mevcut satırlarda başarısız oluyordu:
      * `NOT NULL` sütunlar varsayılansız ekleniyordu
      * tüm `channel` değerleri boş kalacağı için (device_id, channel)
        tekillik kısıtı çakışıyordu
    Bu yüzden sütunlar önce varsayılanla eklenip geri dolduruluyor,
    kısıt en sonda kuruluyor.
    """
    # --- devices: ajan kimliği (hepsi nullable, sorun yok) ---
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.add_column(sa.Column("agent_token_hash", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column("agent_token_created_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("agent_last_seen_at", sa.DateTime(timezone=True), nullable=True)
        )

    # --- peripherals: servo desteği ---
    peripheral_kind = sa.Enum(
        "DIGITAL", "PWM", "SERVO", name="peripheralkind", native_enum=False
    )
    with op.batch_alter_table("peripherals", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("kind", peripheral_kind, nullable=False, server_default="digital")
        )
        batch_op.add_column(
            sa.Column("servo_open_angle", sa.Integer(), nullable=False, server_default="90")
        )
        batch_op.add_column(
            sa.Column("servo_closed_angle", sa.Integer(), nullable=False, server_default="0")
        )

    # --- sensors: kanal tabanlı tanımlama ---
    sensor_kind = sa.Enum(
        "TEMPERATURE", "HUMIDITY", "SOIL_MOISTURE", "PRESSURE",
        "ALTITUDE", "RAIN", "LIGHT", "GENERIC",
        name="sensorkind", native_enum=False,
    )
    with op.batch_alter_table("sensors", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("channel", sa.String(length=80), nullable=False, server_default="")
        )
        batch_op.add_column(
            sa.Column("kind", sensor_kind, nullable=False, server_default="generic")
        )
        batch_op.alter_column("pin", existing_type=sa.INTEGER(), nullable=True)

    # Mevcut sensörlere benzersiz kanal ata. Kimlik zaten benzersiz olduğu için
    # cihaz içinde çakışma imkânsız; kullanıcı sonradan anlamlı ada çevirebilir.
    op.execute(
        """
        UPDATE sensors
           SET channel = 'legacy_' || replace(CAST(id AS CHAR(36)), '-', '')
         WHERE channel IS NULL OR channel = ''
        """
    )

    with op.batch_alter_table("sensors", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_sensors_device_channel", ["device_id", "channel"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sensors_device_channel', type_='unique')
        batch_op.alter_column('pin',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('kind')
        batch_op.drop_column('channel')

    with op.batch_alter_table('peripherals', schema=None) as batch_op:
        batch_op.drop_column('servo_closed_angle')
        batch_op.drop_column('servo_open_angle')
        batch_op.drop_column('kind')

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('agent_last_seen_at')
        batch_op.drop_column('agent_token_created_at')
        batch_op.drop_column('agent_token_hash')

    # ### end Alembic commands ###
